application: is12project
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /juego
  script: juego.app

- url: /gamebroadcast/.*
  script: juego.app

- url: /bdtesting
  script: main.app

- url: /registro
  script: usuarios.app
  
- url: /login
  script: usuarios.app
  
- url: /logout
  script: usuarios.app
    
- url: /isonline
  script: usuarios.app

- url: /salas
  script: salas.app

- url: /salabroadcast/.*
  script: salajuego.app

- url: /busquedasalas
  script: salas.app

- url: /administracion
  script: administracion.app

- url: /salajuego
  script: salajuego.app

- url: /perfil
  script: perfil.app  
  
- url: /mens/.*
  script: perfil.app  
  
- url: /imgs/user
  script: perfil.app
  
- url: /reglas
  script: reglas.app

- url: /ayuda
  script: ayuda.app
  
- url: /.*
  script: main.app

